### ISSUE TITLE
handle the pm2 process restart 

### ISSUE THREAD

**Issue by dcyou** [cheminfo/database-aggregator#27]
we can imagine a solution based on :
http://pm2.keymetrics.io/docs/usage/pm2-doc-single-page/#graceful-reload

**Comment by stropitek** [comment]
Before exiting, cancel all schedulers and wait for the current queue to end. pm2 allows to specify a timeout after which the process will be reloaded anyway

**Comment by stropitek** [comment]
not using pm2 anymore, but we should definitely know what happens with child processes when stopping the parent process

**Comment by stropitek** [comment]
superseded by #52
