### ISSUE TITLE
New scheduler API

### ISSUE THREAD

**Issue by targos** [cheminfo/database-aggregator#42]
Migration to an Adonis API.
WIP at: https://github.com/cheminfo/database-aggregator/tree/api

TODO:
- [x] check if there's a non-hacky way to setup database on startup
- [x] check cors
- [x] check pluggable middleware
- [x] check ssl / port

**Comment by targos** [comment]
New API, with more features:

TODO

**Comment by stropitek** [comment]
anything except server files that I should not bother converting in the typescript branch?
WIP at https://github.com/cheminfo/database-aggregator/tree/use-typescript
