### ISSUE TITLE
io-ts

### ISSUE THREAD

**Issue by stropitek** [cheminfo/database-aggregator#48]
This library allows to check types dynamically with a model that matches the static types.

Interesting for this project because we are loading relatively complex external configuration files.

https://github.com/gcanti/io-ts

**Comment by targos** [comment]
This would need a pretty big refactor of the types. Since it's possible and better to write the configuration in TS (especially for source configs because they depend on a template type), I'm not sure it's worth to do that.

**Comment by stropitek** [comment]
agree it is probably not worth unless we want to use js instead of ts

also some types are already checked manually at runtime anyway
