### ISSUE TITLE
with addition to the intrval of update, is it possible to specify the update time?

### ISSUE THREAD

**Issue by addisalem** [cheminfo/database-aggregator#5]
Can we specify to update fictives and constraints data to be updated each day at 5 a.m.?

or to update ingredients each weekend?

**Comment by stropitek** [comment]
No, the way it was implemented is only based on relative time (i.e. intervals), not on absolute time

**Comment by targos** [comment]
The process scheduler will allow this.
https://github.com/cheminfo/process-scheduler
