### ISSUE TITLE
Support restarts of application during tasks

### ISSUE THREAD

**Issue by targos** [cheminfo/database-aggregator#50]

**Comment by stropitek** [comment]
We expect pm2 to kill the children.

I'm keeping this open.

When switching to node 10 workers could be used instead of child processes.

**Comment by stropitek** [comment]
When database aggregator is starting up, add a new state to all none finished entries in the task history, so that all tasks are flagged as either `success`, `error`, or the new state `interrupted`

**Comment by stropitek** [comment]
Closed with 330e5d693640813efa1ecd3357141eea7355f11b
