### ISSUE TITLE
 Unhandled rejection ValidationError

### ISSUE THREAD

**Issue by addisalem** [cheminfo/database-aggregator#6]
when I run source.js and aggregation.js, I got no error. But, When I use run.js, I got
 Unhandled rejection ValidationError

Detail:
![image](https://cloud.githubusercontent.com/assets/4947365/13284403/5980f786-daf4-11e5-8e68-313a4ab20756.png)

Note that I have disabled brief_jmz in the folder aggregation

**Comment by stropitek** [comment]
Should be fixed by 2c44e7a830ccbd04df3e4482d9a3ad095eac8f56

@addisalem can you confirm?

**Comment by addisalem** [comment]
now it is working
